// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8-k9Iopw6UhKU5pXzca8dNZbDdQbAEA8',
    appId: '1:93889651143:web:8da465bcf58e8ab8f079e2',
    messagingSenderId: '93889651143',
    projectId: 'meu-mes-financas-mc2026',
    authDomain: 'meu-mes-financas-mc2026.firebaseapp.com',
    storageBucket: 'meu-mes-financas-mc2026.firebasestorage.app',
    measurementId: 'G-8TVXG3Q1T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL074wKCV0d83QK5EXk0VEb05Qi15UJus',
    appId: '1:93889651143:android:ae500f8d710af889f079e2',
    messagingSenderId: '93889651143',
    projectId: 'meu-mes-financas-mc2026',
    storageBucket: 'meu-mes-financas-mc2026.firebasestorage.app',
  );
}
